# Name
name: "🌟 Rodar o Yarn, e atualizar os Pacotes"

# Trigger
on: [pull_request]

# Jobs
jobs:
  # Deploy
  deploy:
    # Job name
    name: "✨ Rodar o Yarn, e atualizar os Pacotes"
    # Runs on Ubuntu Latest
    runs-on: ubuntu-latest

    steps:
      # Uses Actions Checkout
      - name: "📜 Rodar o Checkout"
        uses: actions/checkout@v3

      # Setup pNPM
      - name: "📦 Instalar o pNPM e Rodar a instalação dos pacotes"
        uses: pnpm/action-setup@v2.2.1
        with:
          version: "latest"
          run_install: true

      # Configure Node Job
      - name: "🔧 Configurar o Node.JS"
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "pnpm"

      # Run ESLint and Prettier
      - name: "🚧 Rodar o ESLint e o Prettier"
        run: pnpm run lint

      # Build the applications
      - name: "🧱 Construir a aplicação"
        run: pnpm run build